import streamlit as st
import pandas as pd
import plotly.express as px
from database import get_student

from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

# ============================================================
# COLLEGE PLACEMENT ANALYTICS DASHBOARD
# PHASE 1 - BASIC APPLICATION
# ============================================================

# ------------------------------------------------------------
# PAGE CONFIGURATION
# ------------------------------------------------------------

st.set_page_config(
    page_title="Placement Pulse",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ------------------------------------------------------------
# LOAD PLACEMENT DATA
# ------------------------------------------------------------

def create_pdf_report(df):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    story = []

    story.append(
        Paragraph(
            "College Placement Analytics Report",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "Placement Pulse",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 15))

    total_students = len(df)

    placed_students = len(
        df[df["Placement_Status"] == "Placed"]
    )

    placement_rate = (
        placed_students / total_students * 100
        if total_students > 0 else 0
    )

    placed_df = df[
        df["Placement_Status"] == "Placed"
    ]

    average_salary = (
        placed_df["Salary_LPA"].mean()
        if not placed_df.empty else 0
    )

    highest_package = (
        placed_df["Salary_LPA"].max()
        if not placed_df.empty else 0
    )

    story.append(
        Paragraph(
            "Placement Summary",
            styles["Heading2"]
        )
    )

    summary_data = [
        ["Metric", "Value"],
        ["Total Students", str(total_students)],
        ["Placed Students", str(placed_students)],
        ["Placement Rate", f"{placement_rate:.2f}%"],
        ["Average Salary", f"{average_salary:.2f} LPA"],
        ["Highest Package", f"{highest_package:.2f} LPA"]
    ]

    summary_table = Table(
        summary_data,
        colWidths=[250, 180]
    )

    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0),
             colors.HexColor("#232733")),
            ("TEXTCOLOR", (0, 0), (-1, 0),
             colors.white),
            ("GRID", (0, 0), (-1, -1),
             0.5, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 8)
        ])
    )

    story.append(summary_table)
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Branch-wise Placement",
            styles["Heading2"]
        )
    )

    branch_data = [
        ["Branch", "Students", "Placed", "Rate"]
    ]

    for branch in sorted(
        df["Branch"].dropna().unique()
    ):
        branch_df = df[
            df["Branch"] == branch
        ]

        total = len(branch_df)

        placed = len(
            branch_df[
                branch_df["Placement_Status"] == "Placed"
            ]
        )

        rate = (
            placed / total * 100
            if total > 0 else 0
        )

        branch_data.append([
            str(branch),
            str(total),
            str(placed),
            f"{rate:.2f}%"
        ])

    branch_table = Table(
        branch_data,
        colWidths=[130, 100, 100, 100]
    )

    branch_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0),
             colors.HexColor("#232733")),
            ("TEXTCOLOR", (0, 0), (-1, 0),
             colors.white),
            ("GRID", (0, 0), (-1, -1),
             0.5, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 8)
        ])
    )

    story.append(branch_table)
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by Placement Pulse",
            styles["Normal"]
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer

import sqlite3


@st.cache_data
def load_data():
    conn = sqlite3.connect("placement.db")

    data = pd.read_sql_query(
        "SELECT * FROM placements",
        conn
    )

    conn.close()

    return data

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    story = []

    # Title
    story.append(
        Paragraph(
            "College Placement Analytics Report",
            styles["Title"]
        )
    )

    story.append(
        Paragraph(
            "Placement Pulse",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 15))

    # Basic statistics
    total_students = len(df)
    placed_students = len(
        df[df["Placement_Status"] == "Placed"]
    )
    placement_rate = (
        placed_students / total_students * 100
        if total_students > 0 else 0
    )

    placed_df = df[
        df["Placement_Status"] == "Placed"
    ]

    average_salary = (
        placed_df["Salary_LPA"].mean()
        if not placed_df.empty else 0
    )

    highest_package = (
        placed_df["Salary_LPA"].max()
        if not placed_df.empty else 0
    )

    story.append(
        Paragraph("Placement Summary", styles["Heading2"])
    )

    summary_data = [
        ["Metric", "Value"],
        ["Total Students", str(total_students)],
        ["Placed Students", str(placed_students)],
        ["Placement Rate", f"{placement_rate:.2f}%"],
        ["Average Salary", f"{average_salary:.2f} LPA"],
        ["Highest Package", f"{highest_package:.2f} LPA"],
    ]

    summary_table = Table(summary_data, colWidths=[250, 180])

    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#232733")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 8),
        ])
    )

    story.append(summary_table)
    story.append(Spacer(1, 20))

    # Branch report
    story.append(
        Paragraph("Branch-wise Placement", styles["Heading2"])
    )

    branch_data = [
        ["Branch", "Students", "Placed", "Rate"]
    ]

    for branch in sorted(df["Branch"].dropna().unique()):
        branch_df = df[df["Branch"] == branch]

        total = len(branch_df)
        placed = len(
            branch_df[
                branch_df["Placement_Status"] == "Placed"
            ]
        )

        rate = placed / total * 100 if total > 0 else 0

        branch_data.append([
            str(branch),
            str(total),
            str(placed),
            f"{rate:.2f}%"
        ])

    branch_table = Table(
        branch_data,
        colWidths=[130, 100, 100, 100]
    )

    branch_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#232733")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 8),
        ])
    )

    story.append(branch_table)
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "This report is generated from the placement dataset available in Placement Pulse.",
            styles["Normal"]
        )
    )

    doc.build(story)

    buffer.seek(0)
    return buffer

    data = pd.read_csv("data/placement_data.csv")
    return data

df = load_data()

# ------------------------------------------------------------
# DATA VALIDATION
# ------------------------------------------------------------

required_columns = [
    "Student_ID",
    "Student_Name",
    "Branch",
    "CGPA",
    "Skills",
    "Company",
    "Salary_LPA",
    "Placement_Status",
    "Year"
]

missing_columns = [
    column for column in required_columns
    if column not in df.columns
]

if missing_columns:
    st.error(
        f"Missing columns in placement dataset: "
        f"{', '.join(missing_columns)}"
    )
    st.stop()

# ------------------------------------------------------------
# CUSTOM CSS
# ------------------------------------------------------------

st.markdown("""
<style>

    /* Main application */
    .stApp {
        background-color: #0f1117;
    }

    /* Main title */
    .main-title {
        font-size: 42px;
        font-weight: bold;
        text-align: center;
        margin-bottom: 5px;
    }

    .subtitle {
        text-align: center;
        font-size: 18px;
        color: #b8b8b8;
        margin-bottom: 30px;
    }

    /* Feature cards */
    .feature-card {
    padding: 25px;
    border-radius: 18px;
    background: linear-gradient(
        135deg,
        #191c24,
        #222632
    );
    border: 1px solid #30343f;
    min-height: 150px;
    transition: transform 0.25s ease, box-shadow 0.25s ease;
}

.feature-card:hover {
    transform: translateY(-6px);
    box-shadow: 0 12px 30px rgba(0, 0, 0, 0.30);
    border-color: #4b5263;
}

.feature-title {
    font-size: 20px;
    font-weight: 700;
    margin-bottom: 10px;
}

.feature-text {
    color: #b8b8b8;
    font-size: 15px;
    line-height: 1.5;
}

    .feature-title {
        font-size: 20px;
        font-weight: bold;
    }

    .feature-text {
        color: #b8b8b8;
        font-size: 15px;
    }

    /* Footer */
    .footer {
        text-align: center;
        color: #777;
        margin-top: 40px;
        padding: 20px;
    }

        /* Premium KPI Cards */
    [data-testid="stMetric"] {
        background: linear-gradient(
            135deg,
            #191c24,
            #232733
        );
        border: 1px solid #343947;
        border-radius: 16px;
        padding: 20px;
        box-shadow: 0 8px 25px rgba(0, 0, 0, 0.25);
        transition: transform 0.2s ease, border-color 0.2s ease;
    }

    [data-testid="stMetric"]:hover {
        transform: translateY(-3px);
        border-color: #667085;
    }

    [data-testid="stMetricLabel"] {
        font-size: 14px;
        font-weight: 600;
    }

    [data-testid="stMetricValue"] {
    font-size: 32px;
    font-weight: 800;
    letter-spacing: 0.5px;
    }
    
        /* Premium chart containers */
    .stPlotlyChart {
    background: linear-gradient(
        135deg,
        #191c24,
        #222632
    );
    border: 1px solid #30343f;
    border-radius: 18px;
    padding: 12px;
    box-shadow: 0 8px 25px rgba(0, 0, 0, 0.22);
    transition: transform 0.2s ease, border-color 0.2s ease;
}

.stPlotlyChart:hover {
    transform: translateY(-3px);
    border-color: #4b5263;
}

.section-title {
    font-size: 22px;
    font-weight: 700;
    margin-top: 25px;
    margin-bottom: 12px;
    letter-spacing: 0.3px;
}

.section-subtitle {
    color: #9ca3af;
    font-size: 14px;
    margin-bottom: 15px;
}
    
        /* Premium Sidebar */
    section[data-testid="stSidebar"] {
        background-color: #151821;
        border-right: 1px solid #30343f;
    }

    section[data-testid="stSidebar"] h1 {
        font-size: 24px;
        font-weight: 700;
    }

    section[data-testid="stSidebar"] .stRadio label {
        font-size: 15px;
        font-weight: 500;
    }
    .filter-title {
    font-size: 18px;
    font-weight: 700;
    margin-bottom: 10px;
}

.filter-box {
    background: linear-gradient(
        135deg,
        #191c24,
        #222632
    );
    border: 1px solid #30343f;
    border-radius: 14px;
    padding: 15px;
    margin-bottom: 15px;
}   

.filter-text {
    color: #9ca3af;
    font-size: 14px;
}
    
        /* Premium Hero Section */
    .hero-section {
        text-align: center;
        padding: 45px 30px;
        margin-bottom: 25px;
        background: linear-gradient(
            135deg,
            #191c24,
            #232733
        );
        border: 1px solid #343947;
        border-radius: 22px;
        box-shadow: 0 10px 35px rgba(0, 0, 0, 0.25);
    }

    .hero-icon {
        font-size: 55px;
        margin-bottom: 5px;
    }

    .hero-title {
        font-size: 46px;
        font-weight: 800;
        margin-bottom: 5px;
    }

    .hero-subtitle {
        font-size: 20px;
        color: #b8b8b8;
        margin-bottom: 15px;
    }

    .hero-description {
        max-width: 800px;
        margin: auto;
        color: #999;
        font-size: 15px;
        line-height: 1.6;
    }
    .page-header {
    margin-bottom: 25px;
}

.page-header-title {
    font-size: 34px;
    font-weight: 800;
    margin-bottom: 5px;
}

.page-header-subtitle {
    color: #9ca3af;
    font-size: 15px;
}
    
</style>
""", unsafe_allow_html=True)


# ------------------------------------------------------------
# SIDEBAR
# ------------------------------------------------------------

with st.sidebar:

    st.title("🎓 Placement Pulse")

    st.markdown("---")

    st.subheader("Navigation")

    page = st.radio(
        "Go to",
        [
            "🏠 Home",
            "📊 Dashboard",
            "👨‍🎓 Students",
            "📈 Analytics",
            "📁 Data",
            "📋 Reports"
        ]
    )

    st.markdown("---")

    st.caption("College Placement Analytics")
    st.caption("Version 1.0")


# ------------------------------------------------------------
# HOME PAGE
# ------------------------------------------------------------

if page == "🏠 Home":

    st.markdown(
    """
    <div class="hero-section">
        <div class="hero-icon">🎓</div>
        <div class="hero-title">Placement Pulse</div>
        <div class="hero-subtitle">
            College Placement Analytics Dashboard
        </div>
        <div class="hero-description">
            Transform placement data into clear, interactive insights
            across branches, CGPA, skills, companies, salary and years.
        </div>
    </div>
    """,
    unsafe_allow_html=True
)
    st.markdown(
        '<div class="subtitle">'
        'College Placement Analytics Dashboard'
        '</div>',
        unsafe_allow_html=True
    )

    st.divider()

    st.header("Welcome 👋")

    st.write(
        """
        **Placement Pulse** is an interactive College Placement
        Analytics Dashboard designed to analyze placement data
        and convert it into meaningful insights.
        """
    )

    st.write(
        """
        The system will analyze placement statistics based on
        **branch, CGPA, skills, company, salary, and year**.
        """
    )

    st.divider()

    st.subheader("🚀 What This Project Provides")

    # First row
    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown(
            """
            <div class="feature-card">
                <div class="feature-title">
                    🏫 Branch Analysis
                </div>
                <p class="feature-text">
                    Compare placement performance between
                    different engineering branches.
                </p>
            </div>
            """,
            unsafe_allow_html=True
        )

    with col2:
        st.markdown(
            """
            <div class="feature-card">
                <div class="feature-title">
                    📚 CGPA Analysis
                </div>
                <p class="feature-text">
                    Analyze placement trends according to
                    student CGPA.
                </p>
            </div>
            """,
            unsafe_allow_html=True
        )

    with col3:
        st.markdown(
            """
            <div class="feature-card">
                <div class="feature-title">
                    💻 Skills Analysis
                </div>
                <p class="feature-text">
                    Identify popular skills among placed
                    students.
                </p>
            </div>
            """,
            unsafe_allow_html=True
        )

    st.write("")

    # Second row
    col4, col5, col6 = st.columns(3)

    with col4:
        st.markdown(
            """
            <div class="feature-card">
                <div class="feature-title">
                    🏢 Company Analysis
                </div>
                <p class="feature-text">
                    Analyze recruitment patterns and
                    companies hiring students.
                </p>
            </div>
            """,
            unsafe_allow_html=True
        )

    with col5:
        st.markdown(
            """
            <div class="feature-card">
                <div class="feature-title">
                    💰 Salary Analysis
                </div>
                <p class="feature-text">
                    Compare average and highest placement
                    packages.
                </p>
            </div>
            """,
            unsafe_allow_html=True
        )

    with col6:
        st.markdown(
            """
            <div class="feature-card">
                <div class="feature-title">
                    📅 Year-wise Analysis
                </div>
                <p class="feature-text">
                    Track placement performance across
                    multiple years.
                </p>
            </div>
            """,
            unsafe_allow_html=True
        )

    st.divider()

    st.info(
        "💡 More analytics and interactive features will be "
        "added in the upcoming phases."
    )


# ------------------------------------------------------------
# DASHBOARD PAGE
# ------------------------------------------------------------

elif page == "📊 Dashboard":

    st.markdown(
    """
    <div class="page-header">
        <div class="page-header-title">📊 Placement Dashboard</div>
        <div class="page-header-subtitle">
            Interactive overview of college placement performance
        </div>
    </div>
    """,
    unsafe_allow_html=True
    )

    st.write(
        "Overview of college placement performance."
    )

    # --------------------------------------------------------
    # BASIC STATISTICS
    # --------------------------------------------------------

    # Dashboard Filters
    st.subheader("🔎 Dashboard Filters")
    
    st.markdown(
    '<div class="filter-title">Select Filters</div>',
    unsafe_allow_html=True
    )

    st.markdown(
    """
    <div class="filter-box">
        <div class="filter-title">🎛️ Interactive Filters</div>
        <div class="filter-text">
            Use the filters below to explore placement performance.
        </div>
    </div>
    """,
    unsafe_allow_html=True
)

    filter_col1, filter_col2, filter_col3, filter_col4 = st.columns(4)

    with filter_col1:
        selected_branch = st.multiselect(
            "Branch",
            options=sorted(df["Branch"].unique()),
            default=sorted(df["Branch"].unique())
        )

    with filter_col2:
        selected_year = st.multiselect(
            "Year",
            options=sorted(df["Year"].unique()),
            default=sorted(df["Year"].unique())
        )

    with filter_col3:
        selected_company = st.multiselect(
            "Company",
            options=sorted(df["Company"].unique()),
            default=sorted(df["Company"].unique())
        )

    with filter_col4:
        selected_status = st.multiselect(
            "Placement Status",
            options=sorted(df["Placement_Status"].unique()),
            default=sorted(df["Placement_Status"].unique())
        )

    # Apply filters
    filtered_df = df[
        df["Branch"].isin(selected_branch)
        & df["Year"].isin(selected_year)
        & df["Company"].isin(selected_company)
        & df["Placement_Status"].isin(selected_status)
    ]

    total_students = len(filtered_df)

    placed_students = len(
        filtered_df[filtered_df["Placement_Status"] == "Placed"]
    )

    not_placed_students = len(
        filtered_df[filtered_df["Placement_Status"] == "Not Placed"]
    )

    placement_rate = (
        (placed_students / total_students) * 100
        if total_students > 0
        else 0
    )

    # --------------------------------------------------------
    # PLACED STUDENT DATA
    # --------------------------------------------------------

    placed_df = filtered_df[
        filtered_df["Placement_Status"] == "Placed"
    ]

    if len(placed_df) > 0:

        average_salary = placed_df["Salary_LPA"].mean()

        highest_package = placed_df["Salary_LPA"].max()

        recruiting_companies = (
            placed_df["Company"].nunique()
        )

    else:

        average_salary = 0
        highest_package = 0
        recruiting_companies = 0

    # --------------------------------------------------------
    # KPI SECTION
    # --------------------------------------------------------

    st.subheader("📌 Placement Overview")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(
            "👨‍🎓 Total Students",
            f"{total_students:,}"
        )

    with col2:
        st.metric(
            "✅ Placed Students",
            f"{placed_students:,}"
        )

    with col3:
        st.metric(
            "📈 Placement Rate",
            f"{placement_rate:.1f}%"
        )

    col4, col5, col6 = st.columns(3)

    with col4:
        st.metric(
            "💰 Average Salary",
            f"₹{average_salary:.2f} LPA"
        )

    with col5:
        st.metric(
            "🏆 Highest Package",
            f"₹{highest_package:.2f} LPA"
        )

    with col6:
        st.metric(
            "🏢 Recruiting Companies",
            recruiting_companies
        )

    st.divider()

    # --------------------------------------------------------
    # PLACEMENT STATUS
    # --------------------------------------------------------

    st.subheader("📊 Placement Status")

    status_col1, status_col2 = st.columns(2)

    with status_col1:

        st.metric(
            "✅ Placed",
            f"{placed_students:,}"
        )

    with status_col2:

        st.metric(
            "❌ Not Placed",
            f"{not_placed_students:,}"
        )
    
    # --------------------------------------------------------
    # BRANCH-WISE PLACEMENT ANALYSIS
    # --------------------------------------------------------

    st.divider()

    st.subheader("🏫 Branch-wise Placement Analysis")

    branch_analysis = (
        filtered_df.groupby("Branch")
        .agg(
            Total_Students=("Student_ID", "count"),
            Placed_Students=(
                "Placement_Status",
                lambda x: (x == "Placed").sum()
            )
        )
        .reset_index()
    )

    branch_analysis["Placement_Rate"] = (
        branch_analysis["Placed_Students"]
        / branch_analysis["Total_Students"]
    ) * 100

    branch_analysis = branch_analysis.sort_values(
        "Placement_Rate",
        ascending=False
    )

    # --------------------------------------------------------
    # BRANCH CHART
    # --------------------------------------------------------

    fig_branch = px.bar(
        branch_analysis,
        x="Branch",
        y="Placement_Rate",
        text="Placement_Rate",
        title="Placement Rate by Branch"
    )

    fig_branch.update_traces(
        texttemplate="%{text:.1f}%",
        textposition="outside"
    )

    fig_branch.update_layout(
        yaxis_title="Placement Rate (%)",
        xaxis_title="Branch"
    )

    st.plotly_chart(
        fig_branch,
        use_container_width=True
    )

    # --------------------------------------------------------
    # BRANCH SUMMARY TABLE
    # --------------------------------------------------------

    st.subheader("📋 Branch Placement Summary")

    display_branch = branch_analysis.copy()

    display_branch["Placement_Rate"] = (
        display_branch["Placement_Rate"].round(2)
    )

    st.dataframe(
        display_branch,
        use_container_width=True,
        hide_index=True
    )

    # --------------------------------------------------------
    # YEAR-WISE PLACEMENT ANALYSIS
    # --------------------------------------------------------

    st.divider()

    st.subheader("📅 Year-wise Placement Trend")

    # Calculate total and placed students for each year

    year_analysis = (
        filtered_df.groupby("Year")
        .agg(
            Total_Students=("Student_ID", "count"),
            Placed_Students=(
                "Placement_Status",
                lambda x: (x == "Placed").sum()
            )
        )
        .reset_index()
    )

    # Calculate placement rate

    year_analysis["Placement_Rate"] = (
        year_analysis["Placed_Students"]
        / year_analysis["Total_Students"]
    ) * 100

    # Sort by year

    year_analysis = year_analysis.sort_values(
        "Year"
    )

    # --------------------------------------------------------
    # YEAR-WISE LINE CHART
    # --------------------------------------------------------

    fig_year = px.line(
        year_analysis,
        x="Year",
        y="Placement_Rate",
        markers=True,
        title="Placement Rate Trend by Year"
    )

    fig_year.update_traces(
        text=year_analysis["Placement_Rate"].round(1),
    )

    fig_year.update_layout(
        yaxis_title="Placement Rate (%)",
        xaxis_title="Year",
        yaxis_range=[
            0,
            min(100, year_analysis["Placement_Rate"].max() + 10)
        ]
    )

    st.plotly_chart(
        fig_year,
        use_container_width=True
    )

    # --------------------------------------------------------
    # YEAR SUMMARY TABLE
    # --------------------------------------------------------

    st.subheader("📋 Year-wise Placement Summary")

    display_year = year_analysis.copy()

    display_year["Placement_Rate"] = (
        display_year["Placement_Rate"].round(2)
    )

    st.dataframe(
        display_year,   
        use_container_width=True,
        hide_index=True
    )

    # --------------------------------------------------------
    # CGPA-wise placement Analysis
    # --------------------------------------------------------

    st.divider()
    st.subheader("🎓 CGPA-wise Placement Analysis")

    # Create CGPA ranges
    filtered_df["CGPA_Range"] = pd.cut(
        filtered_df["CGPA"],
        bins=[0, 6, 7, 8, 9, 10],
        labels=[
            "Below 6",
            "6 - 7",
            "7 - 8",
            "8 - 9",
            "9 - 10"
        ],
        include_lowest=True
    )

    cgpa_analysis = (
        filtered_df.groupby("CGPA_Range", observed=False)
        .agg(
            Total_Students=("Student_ID", "count"),
            Placed_Students=(
                "Placement_Status",
                lambda x: (x == "Placed").sum()
            )
        )
        .reset_index()
    )

    cgpa_analysis["Placement_Rate"] = (
        cgpa_analysis["Placed_Students"]
        / cgpa_analysis["Total_Students"]
    ) * 100

    # CGPA placement chart
    fig_cgpa = px.bar(
        cgpa_analysis,
        x="CGPA_Range",
        y="Placement_Rate",
        text="Placement_Rate",
        title="Placement Rate by CGPA Range"
    )

    fig_cgpa.update_traces(
        texttemplate="%{text:.1f}%",
        textposition="outside"
    )

    fig_cgpa.update_layout(
        xaxis_title="CGPA Range",
        yaxis_title="Placement Rate (%)",
        yaxis_range=[
            0,
            min(100, cgpa_analysis["Placement_Rate"].max() + 10)
        ]
    )

    st.plotly_chart(
        fig_cgpa,
        use_container_width=True
    )

    # CGPA summary table
    st.subheader("📋 CGPA Placement Summary")

    display_cgpa = cgpa_analysis.copy()

    display_cgpa["Placement_Rate"] = (
        display_cgpa["Placement_Rate"].round(2)
    )

    st.dataframe(
        display_cgpa,
        use_container_width=True,
        hide_index=True
    )

    # --------------------------------------------------------
    # Skills-wise placement Analysis
    # --------------------------------------------------------

    st.divider()
    st.subheader("🛠️ Skills-wise Placement Analysis")

    # Keep only placed students
    placed_skills = filtered_df[
        filtered_df["Placement_Status"] == "Placed"
        ].copy()

    # Split multiple skills into separate rows
    skills = (
        placed_skills["Skills"]
        .dropna()
        .str.split(",")
        .explode()
        .str.strip()
    )

    # Count students for each skill
    skill_analysis = (
        skills.value_counts()
        .reset_index()
    )

    skill_analysis.columns = [
        "Skill",
        "Placed_Students"
    ]

    # Take top 10 skills
    skill_analysis = skill_analysis.head(10)

    # Skills chart
    fig_skills = px.bar(
        skill_analysis,
        x="Placed_Students",
        y="Skill",
        orientation="h",
        text="Placed_Students",
        title="Top 10 Skills Among Placed Students"
    )

    fig_skills.update_traces(
        textposition="outside"
    )

    fig_skills.update_layout(
        xaxis_title="Number of Placed Students",
        yaxis_title="Skill"
    )

    st.plotly_chart(
        fig_skills,
        use_container_width=True
    )

    # Skills summary table
    st.subheader("📋 Skills Placement Summary")

    st.dataframe(
        skill_analysis,
        use_container_width=True,
        hide_index=True
    )

    # --------------------------------------------------------
    # Company-wise placement Analysis
    # --------------------------------------------------------  

    st.divider()
    st.subheader("🏢 Company-wise Placement Analysis")

    company_analysis = (
        filtered_df.groupby("Company")
        .agg(
            Total_Students=("Student_ID", "count"),
            Placed_Students=(
                "Placement_Status",
                lambda x: (x == "Placed").sum()
            ),
            Average_Salary=("Salary_LPA", "mean")
        )
        .reset_index()
    )

    company_analysis["Placement_Rate"] = (
        company_analysis["Placed_Students"]
        / company_analysis["Total_Students"]
    ) * 100

    company_analysis["Average_Salary"] = (
        company_analysis["Average_Salary"].round(2)
    )

    company_analysis["Placement_Rate"] = (
        company_analysis["Placement_Rate"].round(2)
    )

    company_analysis = company_analysis.sort_values(
        "Placement_Rate",
        ascending=False
    )

    fig_company = px.bar(
        company_analysis,
        x="Company",
        y="Placed_Students",
        text="Placed_Students",
        title="Students Placed by Company"
    )

    fig_company.update_traces(
        textposition="outside"
    )

    fig_company.update_layout(
        xaxis_title="Company",
        yaxis_title="Students Placed"
    )

    st.plotly_chart(
        fig_company,
        use_container_width=True
    )

    st.subheader("📋 Company Placement Summary")

    st.dataframe(
        company_analysis,
        use_container_width=True,
        hide_index=True
    )
    st.divider()

    st.subheader("🛠️ Skills Analysis")

    skills_analytics = skill_analysis.copy()
    skills_analytics.columns = [
        "Skill",
        "Placed_Students"
    ]

    skills_analytics = skills_analytics.head(10)

    fig_skills_analytics = px.bar(
        skills_analytics,
        x="Placed_Students",
        y="Skill",
        orientation="h",
        text="Placed_Students",
        title="Top 10 Skills Among Placed Students"
    )

    fig_skills_analytics.update_traces(
        textposition="outside"
    )

    fig_skills_analytics.update_layout(
        xaxis_title="Number of Placed Students",
        yaxis_title="Skill"
    )

    st.plotly_chart(
    fig_skills_analytics,
    use_container_width=True,
    key="skills_analytics_chart"
    )
    

    st.dataframe(
        skills_analytics,
        use_container_width=True,
        hide_index=True
    )
    st.divider()

    st.subheader("📅 Year-wise Salary Trend")

    yearly_salary = (
         filtered_df[
            filtered_df["Placement_Status"] == "Placed"
        ]
        .groupby("Year")
        .agg(
            Average_Salary=("Salary_LPA", "mean"),
            Highest_Salary=("Salary_LPA", "max")
        )
        .reset_index()
    )

    yearly_salary["Average_Salary"] = (
        yearly_salary["Average_Salary"].round(2)
    )

    yearly_salary["Highest_Salary"] = (
        yearly_salary["Highest_Salary"].round(2)
    )

    yearly_salary = yearly_salary.sort_values("Year")

    fig_salary_trend = px.line(
        yearly_salary,
        x="Year",
        y="Average_Salary",
        markers=True,
        text="Average_Salary",
        title="Average Placement Salary by Year"
    )

    fig_salary_trend.update_traces(
        texttemplate="₹%{text:.2f} LPA",
        textposition="top center"
    )

    fig_salary_trend.update_layout(
        xaxis_title="Year",
        yaxis_title="Average Salary (LPA)"
    )

    st.plotly_chart(
        fig_salary_trend,
        use_container_width=True
    )

    st.subheader("📋 Year-wise Salary Summary")

    st.dataframe(
        yearly_salary,
        use_container_width=True,
        hide_index=True
    )

    # --------------------------------------------------------
    # Salary / Package Analysis
    # --------------------------------------------------------
    st.divider()
    st.subheader("💰 Salary / Package Analysis")

    # Salary statistics
    average_salary = filtered_df["Salary_LPA"].mean()
    highest_salary = filtered_df["Salary_LPA"].max()
    lowest_salary = filtered_df["Salary_LPA"].min()

    # Salary KPI cards
    salary_col1, salary_col2, salary_col3 = st.columns(3)

    with salary_col1:
        st.metric(
            "Average Package",
            f"{average_salary:.2f} LPA"
        )

    with salary_col2:
        st.metric(
            "Highest Package",
            f"{highest_salary:.2f} LPA"
        )

    with salary_col3:
        st.metric(
            "Lowest Package",
            f"{lowest_salary:.2f} LPA"
        )

    # Salary distribution
    fig_salary = px.histogram(
        filtered_df,
        x="Salary_LPA",
        nbins=20,
        title="Salary Distribution"
    )

    fig_salary.update_layout(
        xaxis_title="Salary (LPA)",
        yaxis_title="Number of Students"
    )

    st.plotly_chart(
        fig_salary,
        use_container_width=True
    )



    # --------------------------------------------------------
    # DATA PREVIEW
    # --------------------------------------------------------

    st.divider()

    st.subheader("📋 Placement Data Preview")

    st.dataframe(
        df.head(20),
        use_container_width=True,
        hide_index=True
    )

elif page == "👨‍🎓 Students":

    st.markdown(
    """
    <div class="page-header">
        <div class="page-header-title">👨‍🎓 Student Records</div>
        <div class="page-header-subtitle">
            Search, filter and explore individual placement records
        </div>
    </div>
    """,
    unsafe_allow_html=True
)
    st.write("View and search student placement records.")

    st.divider()

    # Search student
    search_student = st.text_input(
        "🔍 Search Student",
        placeholder="Enter student name or Student ID..."
    )

    # Start with complete dataset
    students_df = df.copy()
    
    # Student Filters
    filter_col1, filter_col2, filter_col3 = st.columns(3)

    with filter_col1:
        selected_branch = st.multiselect(
            "🏫 Branch",
            options=sorted(df["Branch"].unique()),
            default=sorted(df["Branch"].unique()),
            key="student_branch"
        )

    with filter_col2:
        selected_year = st.multiselect(
            "📅 Year",
            options=sorted(df["Year"].unique()),
            default=sorted(df["Year"].unique()),
            key="student_year"
        )

    with filter_col3:
        selected_status = st.multiselect(
            "📊 Placement Status",
            options=sorted(df["Placement_Status"].unique()),
            default=sorted(df["Placement_Status"].unique()),
            key="student_status"
        )

    students_df = students_df[
        students_df["Branch"].isin(selected_branch)
        & students_df["Year"].isin(selected_year)
        & students_df["Placement_Status"].isin(selected_status)
    ]

    # Search by name or Student ID
    if search_student:
        search_text = search_student.lower()
        
        students_df = students_df[
            students_df["Student_Name"]
            .astype(str)
            .str.lower()
            .str.contains(search_text, na=False)
            |
            students_df["Student_ID"]
            .astype(str)
            .str.lower()
            .str.contains(search_text, na=False)
            |
            students_df["Company"]
            .astype(str)
            .str.lower()
            .str.contains(search_text, na=False)
            |
            students_df["Skills"]
            .astype(str)
            .str.lower()
            .str.contains(search_text, na=False)
        ]

    st.subheader("📋 Student Records")

    st.write(
        f"Showing **{len(students_df)}** student record(s)"
    )

    st.dataframe(
        students_df,
        use_container_width=True,
        hide_index=True
    )
    
    st.divider()

    st.subheader("👤 Student Details")

    student_ids = students_df["Student_ID"].astype(str).tolist()

    selected_student = st.selectbox(
        "Select Student ID",
        options=["Select a student"] + student_ids
    )

    if selected_student != "Select a student":

        student_info = students_df[
            students_df["Student_ID"].astype(str) == selected_student
        ]

        if not student_info.empty:

            student = student_info.iloc[0]

            detail_col1, detail_col2, detail_col3 = st.columns(3)

            with detail_col1:
                st.metric(
                    "👤 Student",
                    student["Student_Name"]
                )
                st.metric(
                    "🏫 Branch",
                    student["Branch"]
                )
                st.metric(
                    "🎓 CGPA",
                    f"{student['CGPA']:.2f}"
                )

            with detail_col2:
                st.metric(
                    "🏢 Company",
                    student["Company"]
                )
                st.metric(
                    "💰 Salary",
                    f"₹{student['Salary_LPA']:.2f} LPA"
                )
                st.metric(
                    "📅 Year",
                    student["Year"]
                )

            with detail_col3:
                st.metric(
                    "📊 Status",
                    student["Placement_Status"]
                )

                st.write("🛠️ **Skills**")
                st.write(student["Skills"])
# ------------------------------------------------------------
# ANALYTICS PAGE
# ------------------------------------------------------------

elif page == "📈 Analytics":

    st.markdown(
    """
    <div class="page-header">
        <div class="page-header-title">📈 Placement Analytics</div>
        <div class="page-header-subtitle">
            Explore detailed placement trends and performance insights
        </div>
    </div>
    """,
    unsafe_allow_html=True
)

    st.write(
        "Explore detailed placement performance across different categories."
    )

    st.divider()

    # Analytics filters
    st.subheader("🔎 Analytics Filters")

    analytics_col1, analytics_col2 = st.columns(2)

    with analytics_col1:
        analytics_branch = st.selectbox(
            "🏫 Select Branch",
            ["All"] + sorted(df["Branch"].unique())
        )

    with analytics_col2:
        analytics_year = st.selectbox(
            "📅 Select Year",
            ["All"] + sorted(df["Year"].unique())
        )

    # Apply filters
    analytics_df = df.copy()

    if analytics_branch != "All":
        analytics_df = analytics_df[
            analytics_df["Branch"] == analytics_branch
        ]

    if analytics_year != "All":
        analytics_df = analytics_df[
            analytics_df["Year"] == analytics_year
        ]

    # Analytics summary
    total = len(analytics_df)

    placed = len(
        analytics_df[
            analytics_df["Placement_Status"] == "Placed"
        ]
    )

    not_placed = len(
        analytics_df[
            analytics_df["Placement_Status"] == "Not Placed"
        ]
    )

    placement_rate = (
        (placed / total) * 100
        if total > 0
        else 0
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("👨‍🎓 Students", total)

    with col2:
        st.metric("✅ Placed", placed)

    with col3:
        st.metric("❌ Not Placed", not_placed)

    with col4:
        st.metric(
            "📈 Placement Rate",
            f"{placement_rate:.1f}%"
        )

    st.divider()

    # Placement status analysis
    st.subheader("📊 Placement Status Analysis")

    status_analysis = (
        analytics_df["Placement_Status"]
        .value_counts()
        .reset_index()
    )

    status_analysis.columns = [
        "Placement_Status",
        "Students"
    ]

    fig_status = px.pie(
        status_analysis,
        names="Placement_Status",
        values="Students",
        title="Placed vs Not Placed"
    )

    st.plotly_chart(
        fig_status,
        use_container_width=True
    )
    
    st.divider()

    # --------------------------------------------------------
    # SKILLS ANALYSIS
    # --------------------------------------------------------

    st.subheader("🛠️ Skills Analysis")

    skills_df = analytics_df[
        analytics_df["Placement_Status"] == "Placed"
    ].copy()

    if not skills_df.empty:

        skills = (
            skills_df["Skills"]
            .dropna()
            .astype(str)
            .str.split(",")
            .explode()
            .str.strip()
        )

        skills_analysis = (
            skills.value_counts()
            .reset_index()
        )

        skills_analysis.columns = [
            "Skill",
            "Placed_Students"
        ]

        skills_analysis = skills_analysis.head(10)

        fig_skills = px.bar(
            skills_analysis.sort_values(
                "Placed_Students"
            ),
            x="Placed_Students",
            y="Skill",
            orientation="h",
            title="Top 10 Skills Among Placed Students",
            text="Placed_Students"
        )

        st.plotly_chart(
            fig_skills,
            use_container_width=True
        )

        st.dataframe(
            skills_analysis,
            use_container_width=True,
            hide_index=True
        )

    else:

        st.info(
            "No placed students available for the selected filters."
        )

    st.divider()

    st.subheader("🎓 CGPA vs Placement")

    analytics_df["CGPA_Range"] = pd.cut(
        analytics_df["CGPA"],
        bins=[0, 6, 7, 8, 9, 10],
        labels=[
            "Below 6",
            "6 - 7",
            "7 - 8",
            "8 - 9",
            "9 - 10"
        ],
        include_lowest=True
    )

    cgpa_analytics = (
        analytics_df.groupby(
            "CGPA_Range",
            observed=False
        )
        .agg(
            Total_Students=("Student_ID", "count"),
            Placed_Students=(
                "Placement_Status",
                lambda x: (x == "Placed").sum()
            )
        )
        .reset_index()
    )

    cgpa_analytics["Placement_Rate"] = (
        cgpa_analytics["Placed_Students"]
        / cgpa_analytics["Total_Students"]
    ) * 100

    fig_cgpa_analytics = px.bar(
        cgpa_analytics,
        x="CGPA_Range",
        y="Placement_Rate",
        text="Placement_Rate",
        title="Placement Rate by CGPA Range"
    )

    fig_cgpa_analytics.update_traces(
        texttemplate="%{text:.1f}%",
        textposition="outside"
    )

    fig_cgpa_analytics.update_layout(
        xaxis_title="CGPA Range",
        yaxis_title="Placement Rate (%)"
    )

    st.plotly_chart(
        fig_cgpa_analytics,
        use_container_width=True
    )
    st.divider()

    st.subheader("🏢 Company-wise Salary Analysis")

    company_analytics = (
        analytics_df[
            analytics_df["Placement_Status"] == "Placed"
        ]
        .groupby("Company")
        .agg(
            Students_Placed=("Student_ID", "count"),
            Average_Salary=("Salary_LPA", "mean"),
            Highest_Salary=("Salary_LPA", "max")
        )
        .reset_index()
    )

    company_analytics["Average_Salary"] = (
        company_analytics["Average_Salary"].round(2)
    )

    company_analytics["Highest_Salary"] = (
        company_analytics["Highest_Salary"].round(2)
    )

    company_analytics = company_analytics.sort_values(
        "Average_Salary",
        ascending=False
    )

    fig_company_salary = px.bar(
        company_analytics,
        x="Company",
        y="Average_Salary",
        text="Average_Salary",
        title="Average Salary by Company"
    )

    fig_company_salary.update_traces(
        texttemplate="₹%{text:.2f} LPA",
        textposition="outside"
    )

    fig_company_salary.update_layout(
        xaxis_title="Company",
        yaxis_title="Average Salary (LPA)"
    )

    st.plotly_chart(
        fig_company_salary,
        use_container_width=True
    )

    st.subheader("📋 Company Salary Summary")

    st.dataframe(
        company_analytics,
        use_container_width=True,
        hide_index=True
    )

# ------------------------------------------------------------
# DATA PAGE
# ------------------------------------------------------------

# ------------------------------------------------------------
# DATA PAGE
# ------------------------------------------------------------

elif page == "📁 Data":

    st.markdown(
    """
    <div class="page-header">
        <div class="page-header-title">📁 Placement Data</div>
        <div class="page-header-subtitle">
            Upload, preview and inspect placement datasets
        </div>
    </div>
    """,
    unsafe_allow_html=True
)

    st.write(
        "Upload a CSV placement dataset and preview its contents."
    )

    st.divider()

    # Upload CSV
    st.subheader("📤 Upload Placement Dataset")

    uploaded_file = st.file_uploader(
        "Choose a CSV file",
        type=["csv"]
    )

    if uploaded_file is not None:

        try:
            uploaded_df = pd.read_csv(uploaded_file)

            st.success(
                "✅ CSV file uploaded successfully!"
            )

            # Required columns
            required_columns = [
                "Student_ID",
                "Student_Name",
                "Branch",
                "CGPA",
                "Skills",
                "Company",
                "Salary_LPA",
                "Placement_Status",
                "Year"
            ]

            missing_columns = [
                column
                for column in required_columns
                if column not in uploaded_df.columns
            ]

            if missing_columns:

                st.error(
                    "❌ Missing columns: "
                    + ", ".join(missing_columns)
                )

            else:

                st.success(
                    "✅ Dataset structure is valid!"
                )

                # Dataset information
                data_col1, data_col2, data_col3 = st.columns(3)

                with data_col1:
                    st.metric(
                        "👨‍🎓 Total Students",
                        len(uploaded_df)
                    )

                with data_col2:
                    st.metric(
                        "📊 Total Columns",
                        len(uploaded_df.columns)
                    )

                with data_col3:
                    st.metric(
                        "🏢 Companies",
                        uploaded_df["Company"].nunique()
                    )

                st.divider()

                # Preview
                st.subheader("📋 Dataset Preview")

                st.dataframe(
                    uploaded_df.head(20),
                    use_container_width=True,
                    hide_index=True
                )

                st.divider()

                # Column information
                st.subheader("🧾 Dataset Columns")

                column_info = pd.DataFrame({
                    "Column": uploaded_df.columns,
                    "Data Type": [
                        str(uploaded_df[column].dtype)
                        for column in uploaded_df.columns
                    ],
                    "Missing Values": [
                        uploaded_df[column].isna().sum()
                        for column in uploaded_df.columns
                    ]
                })

                st.dataframe(
                    column_info,
                    use_container_width=True,
                    hide_index=True
                )

        except Exception as e:

            st.error(
                f"❌ Unable to read the CSV file: {e}"
            )

    else:

        st.info(
            "👆 Upload a CSV file to view and analyze the dataset."
        )


# ------------------------------------------------------------
# REPORT PAGE
# ------------------------------------------------------------

elif page == "📋 Reports":

    st.markdown(
    """
    <div class="page-header">
        <div class="page-header-title">📋 Placement Reports</div>
        <div class="page-header-subtitle">
            Generate a concise summary of placement performance
        </div>
    </div>
    """,
    unsafe_allow_html=True
    )

    st.write(
        "Generate a quick summary of the college placement performance."
    )

    st.divider()

    # Report KPIs
    total_students = len(df)

    placed_students = len(
        df[df["Placement_Status"] == "Placed"]
    )

    not_placed_students = len(
        df[df["Placement_Status"] != "Placed"]
    )

    placement_rate = (
        placed_students / total_students * 100
        if total_students > 0
        else 0
    )

    average_salary = df[
        df["Placement_Status"] == "Placed"
    ]["Salary_LPA"].mean()

    highest_salary = df[
        df["Placement_Status"] == "Placed"
    ]["Salary_LPA"].max()

    report_col1, report_col2, report_col3 = st.columns(3)

    with report_col1:
        st.metric(
            "👨‍🎓 Total Students",
            total_students
        )

    with report_col2:
        st.metric(
            "✅ Placed Students",
            placed_students
        )

    with report_col3:
        st.metric(
            "📈 Placement Rate",
            f"{placement_rate:.2f}%"
        )

    st.divider()

    report_col4, report_col5 = st.columns(2)

    with report_col4:
        st.metric(
            "💰 Average Salary",
            f"{average_salary:.2f} LPA"
        )

    with report_col5:
        st.metric(
            "🏆 Highest Package",
            f"{highest_salary:.2f} LPA"
        )

    st.divider()

    # Branch-wise report
    st.subheader("🏫 Branch-wise Placement Report")

    branch_report = (
        df.groupby("Branch")
        .agg(
            Total_Students=("Student_ID", "count"),
            Placed_Students=(
                "Placement_Status",
                lambda x: (x == "Placed").sum()
            ),
            Average_Salary=(
                "Salary_LPA",
                "mean"
            )
        )
        .reset_index()
    )

    branch_report["Placement_Rate"] = (
        branch_report["Placed_Students"]
        / branch_report["Total_Students"]
        * 100
    )

    branch_report["Average_Salary"] = (
        branch_report["Average_Salary"].round(2)
    )

    branch_report["Placement_Rate"] = (
        branch_report["Placement_Rate"].round(2)
    )

    st.dataframe(
        branch_report,
        use_container_width=True,
        hide_index=True
    )

    st.divider()

    # Company-wise report
    st.subheader("🏢 Company-wise Placement Report")

    company_report = (
        df[df["Placement_Status"] == "Placed"]
        .groupby("Company")
        .agg(
            Students_Placed=("Student_ID", "count"),
            Average_Salary=("Salary_LPA", "mean"),
            Highest_Salary=("Salary_LPA", "max")
        )
        .reset_index()
    )

    company_report["Average_Salary"] = (
        company_report["Average_Salary"].round(2)
    )

    company_report["Highest_Salary"] = (
        company_report["Highest_Salary"].round(2)
    )

    st.dataframe(
        company_report,
        use_container_width=True,
        hide_index=True
    )
    st.download_button(
    label="📥 Download Placement Report",
    data=df.to_csv(index=False).encode("utf-8"),
    file_name="placement_report.csv",
    mime="text/csv"
    )
    pdf_file = create_pdf_report(df)

from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

pdf_buffer = BytesIO()

c = canvas.Canvas(pdf_buffer, pagesize=A4)

c.setFont("Helvetica-Bold", 18)
c.drawString(50, 800, "College Placement Analytics Report")

c.setFont("Helvetica", 11)
c.drawString(50, 770, "Placement Analytics Dashboard")

c.drawString(50, 740, "This report contains the placement analysis generated from the dashboard.")

c.save()

pdf_buffer.seek(0)
pdf_file = pdf_buffer.getvalue()

st.download_button(
    label="📄 Download PDF Report",
    data=pdf_file,
    file_name="placement_report.pdf",
    mime="application/pdf"
)
st.success(
        "✅ Placement report generated successfully!"
    )

# ------------------------------------------------------------
# FOOTER
# ------------------------------------------------------------

st.markdown(
    """
    <div class="footer">
        🎓 Placement Pulse |
        College Placement Analytics Dashboard
        <br>
        Developed as a College Project
    </div>
    """,
    unsafe_allow_html=True
)
